name: Simple Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo test
        run: echo "Hello World - Workflow is working!"
        
      - name: List files
        run: ls -la